### ISSUE TITLE
Header border not showing up on 2.2.0

### ISSUE THREAD

**Issue by leoorloski** [klembot/chapbook#208]
I'm using the header to show some resources for a project I'm making, it looks like this:

`config.header.left: "FUEL: {fuelV}&emsp;&emsp;FOOD: {foodV}"`
`config.header.center: "GUARDS: {guardsV}&emsp;&emsp;PEOPLE: {peopleV}"`
`config.header.right: "MACHINES: {machinesV}"`

Everything works fine, but the border that separates the header from the main text doesn't appear. If I change Chapbook's version to 1.2.3, the border appears as expected.

**Comment by klembot** [comment]
To work around this bug, put this in your story stylesheet:

```css
#page > marginal-content[type="header"] {
  border-bottom: var(--page-header-border);
}
```
